theme = "minimal"  # Use the minimal theme as the base
baseURL = "https://hkusttech.github.io/"
languageCode = "en-us"
title = "HKUST Tech Club"
disqusShortname = "https-hkusttech-github-io" # delete this to disable disqus comments
#googleAnalytics = ""

[taxonomies]
  tag = "tags"

[params]
    author = "HKUST Tech Club team"
    description = "Connecting HKUST Tech Talent"
    githubUsername = "hkpeterpeter"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "java", "javascript"]
    copyright = "HKUST Tech Club team 2018"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/events"
    name = "Events"
    weight = 2

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 3

[[menu.icon]]
        url = "mailto:hkusttech@gmail.com"
        name = "envelope-o"
        weight = 1

[[menu.icon]]
        url = "https://www.facebook.com/groups/191514444767596/"
        name = "facebook-f"
        weight = 2

[[menu.icon]]
        url = "https://hkusttechclub.slack.com"
        name = "slack"
        weight = 3

[[menu.icon]]
        url = "https://github.com/hkusttech"
        name = "github"
        weight = 4
